app:
  name: ms-user-profile
  profiles: standalone

security:
  jwt:
    secret: my-super-secret

data:
  jdbc:
    gorm:
      logger:
        level: "INFO"
  datasource:
    postgres:
      host: localhost
      port: 5432
      user: admin
      password: password
      database: users

server:
  port: 8080
  read-timeout: 10
  write-timeout: 10
