app:
  name: ms-user-profile
  environment: ${ENV:standalone}

data:
  jdbc:
    gorm:
      logger:
        level: "INFO"
  datasource:
    postgres:
      host: ${POSTGRES_HOST:localhost}
      port: ${POSTGRES_PORT:5432}
      user: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:password}
      database: users

server:
  port: 8080
  read-timeout: 10
  write-timeout: 10
